### ISSUE TITLE
refundNonContractShipment 404s

### ISSUE THREAD

**Issue by ssshake** [t3rminus/canada-post#13]
I think the api path might have changed since this was implemented. I cannot refund any shipments. 

```

CanadaPostError: The requested URL /ct/ext/ncshipment/717251649873209304 was not found on this server.
    at CanadaPostClient._rawRequest (...\node_modules\canadapost-api\lib\canadapost.js:121:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async CanadaPostClient.getShipment (...\node_modules\canadapost-api\lib\canadapost.js:320:18)
    at async CanadaPostClient.refundNonContractShipment (...\node_modules\canadapost-api\lib\canadapost.js:201:22) {
  code: '404',
  originalMessages: [
    {
      code: '404',
      description: 'The requested URL /ct/ext/ncshipment/717251649873209304 was not found on this server.'
    }
  ]
}

```

**Comment by ssshake** [comment]
bump

**Comment by t3rminus** [comment]
It's possible your shipment IDs are being removed through some other means, or your particular shipments are not valid for refund. I am able to refund shipments without issue.

As this is not an issue with the library, please contact Canada Post for assistance.
