### ISSUE TITLE
For Destination unitedStates, the Canada-post API may not always return ''Options" 

### ISSUE THREAD

**Issue by rohan-sethi** [t3rminus/canada-post#3]
```
(node:6954) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'option' of undefined
    at result.map.r (/home/rohan/projects/mashkiki/mashkiki/node_modules/canadapost-api/lib/canadapost.js:157:37)
    at Array.map (<anonymous>)
    at CanadaPostClient.getRates (/home/rohan/projects/mashkiki/mashkiki/node_modules/canadapost-api/lib/canadapost.js:154:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6954) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6954) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

A check in the API is must, something like -

```
	return result.map(r => {
			delete r.serviceLink;
			r.priceDetails.adjustments = r.priceDetails.adjustments.adjustment;
			if(typeof r.priceDetails.options != 'undefined')
			r.priceDetails.options = r.priceDetails.options.option;
			else
			r.priceDetails.options = {};

			return r;
		});
```

**Comment by t3rminus** [comment]
I just published 1.0.5, and this issue should be resolved.
